project_id = "vxlrqfrisowqfuscodzt"

[functions.create_order]
verify_jwt = true

[functions.verify_payment]
verify_jwt = true

[functions.razorpay_webhook]
verify_jwt = false

[functions.initiate_withdrawal]
verify_jwt = true

[functions.razorpay_payout_webhook]
verify_jwt = false
