import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Brain,
  FileText,
  AlertTriangle,
  CheckCircle2,
  Activity,
  Upload,
  Clock,
  Shield,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

interface SampleReportPreviewProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const SAMPLE_FINDINGS = [
  {
    type: "Abnormal",
    severity: "moderate",
    label: "Intermittent focal slowing",
    location: "Left temporal (T3-T5)",
    detail:
      "Intermittent polymorphic delta activity (2-3 Hz) observed in the left temporal region, more prominent during drowsiness.",
  },
  {
    type: "Abnormal",
    severity: "mild",
    label: "Mild diffuse background slowing",
    location: "Generalized",
    detail:
      "Posterior dominant rhythm at 7.5 Hz (mildly slow for age). Background organization preserved.",
  },
  {
    type: "Normal",
    severity: "normal",
    label: "Sleep architecture intact",
    location: "Generalized",
    detail:
      "Vertex waves, sleep spindles, and K-complexes appropriately identified. No epileptiform discharges during sleep.",
  },
];

const SAMPLE_SEGMENTS = [
  { time: "00:03:24", duration: "4.2s", type: "Focal slowing", channel: "T3-T5" },
  { time: "00:07:51", duration: "2.8s", type: "Theta burst", channel: "F7-T3" },
  { time: "00:14:12", duration: "6.1s", type: "Delta activity", channel: "T3-T5" },
];

export default function SampleReportPreview({
  open,
  onOpenChange,
}: SampleReportPreviewProps) {
  const navigate = useNavigate();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Sample Triage Report
          </DialogTitle>
          <DialogDescription>
            This is an example of what your AI-generated triage report looks
            like
          </DialogDescription>
        </DialogHeader>

        {/* Report Header */}
        <div className="rounded-xl border bg-muted/30 p-4 space-y-3">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <div>
              <p className="text-sm font-semibold">ENCEPHLIAN Triage Report</p>
              <p className="text-xs text-muted-foreground">
                Generated by MIND® AI Engine v2.4
              </p>
            </div>
            <Badge variant="outline" className="text-xs gap-1">
              <Shield className="h-3 w-3" />
              Sample
            </Badge>
          </div>
          <Separator />
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div>
              <p className="text-muted-foreground">Patient</p>
              <p className="font-medium">J. Doe (62y/M)</p>
            </div>
            <div>
              <p className="text-muted-foreground">Recording</p>
              <p className="font-medium">21ch · 256Hz · 32 min</p>
            </div>
            <div>
              <p className="text-muted-foreground">Priority</p>
              <p className="font-medium">Standard (TAT)</p>
            </div>
            <div>
              <p className="text-muted-foreground">Completed</p>
              <p className="font-medium">18 min after upload</p>
            </div>
          </div>
        </div>

        {/* Clinical Summary */}
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Brain className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-semibold">Clinical Summary</h3>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Routine EEG (32 min) showing{" "}
            <strong className="text-foreground">
              intermittent focal slowing in the left temporal region
            </strong>{" "}
            with mild diffuse background slowing. No epileptiform discharges
            identified. Sleep architecture is intact. Findings suggest possible
            underlying structural or functional abnormality in the left temporal
            lobe. Clinical correlation recommended.
          </p>
        </div>

        {/* Findings */}
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-semibold">Key Findings</h3>
          </div>
          <div className="space-y-2">
            {SAMPLE_FINDINGS.map((finding, i) => (
              <div
                key={i}
                className="p-3 rounded-lg border bg-background space-y-1.5"
              >
                <div className="flex items-center gap-2 flex-wrap">
                  {finding.severity === "normal" ? (
                    <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                  ) : (
                    <AlertTriangle
                      className={`h-3.5 w-3.5 ${
                        finding.severity === "moderate"
                          ? "text-amber-500"
                          : "text-yellow-500"
                      }`}
                    />
                  )}
                  <span className="text-sm font-medium">{finding.label}</span>
                  <Badge
                    variant={
                      finding.severity === "normal" ? "secondary" : "outline"
                    }
                    className="text-[10px] px-1.5 py-0"
                  >
                    {finding.severity}
                  </Badge>
                  <span className="text-[10px] text-muted-foreground ml-auto">
                    {finding.location}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {finding.detail}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Annotated segments */}
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-semibold">Annotated Segments</h3>
            <span className="text-xs text-muted-foreground">
              ({SAMPLE_SEGMENTS.length} segments flagged)
            </span>
          </div>
          <div className="rounded-lg border overflow-hidden">
            <div className="grid grid-cols-4 gap-2 p-2 bg-muted/50 text-[10px] font-medium text-muted-foreground">
              <span>Time</span>
              <span>Duration</span>
              <span>Type</span>
              <span>Channel</span>
            </div>
            {SAMPLE_SEGMENTS.map((seg, i) => (
              <div
                key={i}
                className="grid grid-cols-4 gap-2 p-2 text-xs border-t"
              >
                <span className="font-mono tabular-nums">{seg.time}</span>
                <span>{seg.duration}</span>
                <span className="font-medium">{seg.type}</span>
                <span className="text-muted-foreground">{seg.channel}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Impression */}
        <div className="rounded-xl border-2 border-primary/20 bg-primary/5 p-4 space-y-2">
          <h3 className="text-sm font-semibold flex items-center gap-2">
            <Brain className="h-4 w-4 text-primary" />
            Impression
          </h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            <strong className="text-foreground">Abnormal EEG.</strong>{" "}
            Intermittent left temporal focal slowing with mild generalized
            background slowing. No epileptiform discharges. Consider MRI brain
            with attention to left temporal lobe. Repeat EEG if clinical
            suspicion for seizures persists.
          </p>
        </div>

        {/* CTA */}
        <div className="flex flex-col sm:flex-row gap-2 pt-1">
          <Button
            onClick={() => {
              onOpenChange(false);
              navigate("/app/studies");
            }}
            className="flex-1 gap-2 rounded-full"
          >
            <Upload className="h-4 w-4" />
            Upload Your EEG Now
          </Button>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            className="flex-1 rounded-full"
          >
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
